[package]
name = "stuff"
version = "0.1.0"
authors = ["giusdp <depalma.gsp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "mergesort"

[[example]]
name = "twosum"